### ISSUE TITLE
seinfo --permissive yields incorrect results

### ISSUE THREAD

**Issue by stephensmalley** [TresysTechnology/setools#112]
seinfo reports 1 permissive in statistics but none when asked for a list:
$ seinfo n-sepolicy 
Couldn't import dot_parser, loading of dot files will not be possible.
Statistics for policy file: n-sepolicy
Policy Version: 30 (MLS enabled, deny unknown permissions)
  Classes:            55    Permissions:       285
  Sensitivities:       1    Categories:       1024
  Types:             708    Attributes:         26
  Users:               1    Roles:               2
  Booleans:            0    Cond. Expr.:         0
  Allow:            6281    Neverallow:          0
  Auditallow:         12    Dontaudit:         102
  Type_trans:        235    Type_change:         0
  Type_member:         0    Range_trans:         0
  Role allow:          0    Role_trans:          0
  Constraints:         0    Validatetrans:       0
  MLS Constrain:      51    MLS Val. Tran:       0
  Initial SIDs:       27    Fs_use:             16
  Genfscon:           44    Portcon:             0
  Netifcon:            0    Nodecon:             0
  Permissives:         1    Polcap:              2
  Defaults:            0    Typebounds:          0

$ seinfo --permissive n-sepolicy
Couldn't import dot_parser, loading of dot files will not be possible.

Permissive Types: 0

Confirmed that there is in fact a permissive domain there:
$ sepolicy-analyze n-sepolicy permissive
cameraserver

**Comment by doverride** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 03/17/2016 07:06 PM, stephensmalley wrote:
> seinfo reports 1 permissive in statistics but none when asked for a
> list: $ seinfo n-sepolicy Couldn't import dot_parser, loading of
> dot files will not be possible. Statistics for policy file:
> n-sepolicy Policy Version: 30 (MLS enabled, deny unknown
> permissions) Classes:            55    Permissions:       285 
> Sensitivities:       1    Categories:       1024 Types:
> 708    Attributes:         26 Users:               1    Roles:
> 2 Booleans:            0    Cond. Expr.:         0 Allow:
> 6281    Neverallow:          0 Auditallow:         12    Dontaudit:
> 102 Type_trans:        235    Type_change:         0 Type_member:
> 0    Range_trans:         0 Role allow:          0    Role_trans:
> 0 Constraints:         0    Validatetrans:       0 MLS Constrain:
> 51    MLS Val. Tran:       0 Initial SIDs:       27    Fs_use:
> 16 Genfscon:           44    Portcon:             0 Netifcon:
> 0    Nodecon:             0 Permissives:         1    Polcap:
> 2 Defaults:            0    Typebounds:          0
> 
> $ seinfo --permissive n-sepolicy Couldn't import dot_parser,
> loading of dot files will not be possible.
> 
> Permissive Types: 0
> 
> Confirmed that there is in fact a permissive domain there: $
> sepolicy-analyze n-sepolicy permissive cameraserver
> 

seems to work fine for me (although i am not pointing it to a policy
.. instead i am using /sys/fs/selinux/policy)

https://www.youtube.com/watch?v=repcGBH-BAg


- -- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQGcBAEBCAAGBQJW6vgdAAoJECV0jlU3+Udpu2QL/j1zqHUTchxubrLt3uovnuZq
JZ776qJoY4Vv2DNfXsJ+iwzFmxPymGgJ6zia98nhDkkRGAjOqBjHx4h7y9rwMboE
SyzfqiUkd/D1Nc9EIu2P0Vt4J+I7PtmEEB9ln57XiAqiHx4RnfpSZ6XZSEsk0XRL
FByXfYjLW0FT4CXIOAN4RElxESxxsTQ/0XIhOzVboj00X2jtkdvZGdT3uO99jUAY
7yax+FwAy246oSrNZ4/1FIYFrTHYTv8l9kBCX7xq9WzhBtVNfZHQ5K5VHJWtNmyN
8mtuiEl6ikcNq2fwkUtm4mLvj9qWMp6mYziUlLM9FYqj8YUKSz+VAdDHQKRqPnKi
9QFEbrA71tIU9U8yCGM5ZHmlMsQGfMidWPbODcsETSlZZl1ulI9Qkjo3YMDj7+PH
KEyq2AzIvxNiZkpx+raVt9AhnTItHY6hv/n2l1UdiAVXqe7GUevnigXAP9A0cb+n
jey3jtbxf91QrToG4UCW2PlhbY0gNgvcLcNndk6KdQ==
=wxQj
-----END PGP SIGNATURE-----

**Comment by stephensmalley** [comment]
Actually, I get 0 results for any seinfo query, e.g.
 seinfo --type n-sepolicy 
Couldn't import dot_parser, loading of dot files will not be possible.

Types: 0

But if I give it a specific type, that works:
$ seinfo --type zygote n-sepolicy 
Couldn't import dot_parser, loading of dot files will not be possible.

Types: 1
   zygote

This is on a policy version 30 file.

**Comment by doverride** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 03/17/2016 07:34 PM, stephensmalley wrote:
> Actually, I get 0 results for any seinfo query, e.g. seinfo --type
> n-sepolicy Couldn't import dot_parser, loading of dot files will
> not be possible.
> 
> Types: 0
> 
> But if I give it a specific type, that works: $ seinfo --type
> zygote n-sepolicy Couldn't import dot_parser, loading of dot files
> will not be possible.
> 
> Types: 1 zygote
> 
> This is on a policy version 30 file.

policy.30 does not work yet with setools

> 
> 
> 
y fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQGcBAEBCAAGBQJW6vjhAAoJECV0jlU3+Udp+ekMAJj1LvzpBwkx63ckjCoex8gh
eMAy5fIwRWvK/daFS0n7MzvVhu+puqtoiKWQLzrnJfLUjFLrf7CUxttR+D+RmdVe
aGHZf4JoHKKRale7chnecude6ZEPbHF2AntGnJG+8+UiKV0rGNZXMoxLvzY9JkIo
pvemZpttBEQOI9uBNrQD+9edCFWeuO2pn42YlOLu7XUPmM2vz02qpVBq40e5tW7e
hHsgE0Bk6zg3//yO+fHhxkEXCzS1a14ofHbdOgBBhXJQ22xNaPAZGB8OOyOo2khS
2d7a4AxQQ8DUOvgHy871ixRfde0/lW8140VVcHLPoXSUPtyG+hn60JXqKp91JwQS
78OC4I++5CpHlfv5Tnm1410kSQLbKDt2SRTNQU+iw3gabk2Y7/g+pIgt7ebh+hFm
4iSNvejAiz5XPC7x6iXRfKpqU0O4H1nYIi0WMv2SxKuvxJoy9OvBPEi7mdMtSBEb
xpzofMCZPINSX+YEuc4xnUN8BsPbZ2KjfOYhsLozaw==
=oqqn
-----END PGP SIGNATURE-----

**Comment by stephensmalley** [comment]
Actually, it seems to be a problem with passing seinfo a policy path on the command line.
Pass a pathname and it does not work, even if that pathname is /sys/fs/selinux/policy.

**Comment by pebenito** [comment]
This looks like you're getting bitten by the Python command line parser. The command line options have optional arguments, so it chooses them over specifying a policy. e.g.

* ```seinfo --permissive``` means get all permissive types from ```/sys/fs/selinux/policy```
* ```seinfo --permissive sepolicy``` means look for a permissive type called ```sepolicy``` from ```/sys/fs/selinux/policy```
* ```seinfo sepolicy --permissive``` means get all permissive types from the ```sepolicy``` file.
* ```seinfo sepolicy --permissive system_server``` means look or a permissive type called ```system_server``` from the ```sepolicy``` file.
* ```seinfo --permissive -x sepolicy``` means get all permissive types from the ```sepolicy``` file and print additional info on them.

This is what drove the setools3 behavior of seinfo where you couldn't put a space between the CLI switch and the parameter, eg ```seinfo -tkernel_t```. I don't know that I could make it prefer specifying the policy over specifying the optional argument for --permissive.

**Comment by stephensmalley** [comment]
Ok, confirmed that seinfo n-sepolicy --permissive works.  So I guess it is not a bug.

**Comment by pebenito** [comment]
I'll document minor CLI interface changes like this.
