### ISSUE TITLE
sediff: improve memory usage

### ISSUE THREAD

**Issue by d3vilbox** [TresysTechnology/setools#127]
SETools 4, Fedora 24 4GB/8GB memory

I tried to run sediff on the rhel 7 targeted policy and a custom policy and sediff is killed by the oom killer. I initially tried this on a VM with 4GB of memory and then increased it to 8GB of memory and it was killed both times. 

I can review things further if it will help debug.

[ 1165.987596] Out of memory: Kill process 1409 (sediff) score 966 or sacrifice child
[ 1165.987620] Killed process 1409 (sediff) total-vm:10247980kB, anon-rss:7886488kB, file-rss:1584kB, shmem-rss:0kB

This memory problem is probably due to the fact that sediff is storing the differences instead of outputting them as it goes. I used the old version of setools on a system with 32GB of memory and found that the output file was 25660419 lines long. The new version of sediff also seems to use more memory than the old version but I found that both the old and new version fail to run with 8GB or less of memory.

**Comment by pebenito** [comment]
The focus of SETools development thus far has been correct results. Performance and memory usage will be tackled in future versions (post 4.0).
