### ISSUE TITLE
Problem with build on Fedora Rawhide i386 with python-2.7

### ISSUE THREAD

**Issue by bachradsusi** [TresysTechnology/setools#139]
I've tried to build setools-4.0.0 on Fedora Rawhide using http://pkgs.fedoraproject.org/cgit/rpms/setools.git/tree/setools.spec?h=private-plautrba-4.0.0 and it fails on i386, see https://copr.fedorainfracloud.org/coprs/plautrba/setools4/build/183221/ resp https://copr-be.cloud.fedoraproject.org/results/plautrba/setools4/fedora-rawhide-i386/00183221-setools4/build.log.gz

**Comment by pebenito** [comment]
I don't immediately have a 32bit system handy. Can you try the SETools master branch? There is a fix for MacOS X that might fix this too.

**Comment by pebenito** [comment]
I believe d6996d1f09cc104aa150e8ce5c8c0becaceca662 will fix this.

**Comment by bachradsusi** [comment]
You are right. It's already fixed in master. Thanks!

**Comment by pebenito** [comment]
Confirmed the above commit is the fix for this issue. Merged to 4.0 branch for future 4.0.1 release.
