### ISSUE TITLE
setup.py errors if sepol not installed

### ISSUE THREAD

**Issue by williamcroberts** [TresysTechnology/setools#147]
Relates to #138 
Following the instructions on the README results in:

`$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    static_sepol = dynamic_sepol.replace(".so", ".a")
AttributeError: 'NoneType' object has no attribute 'replace'
`

libsepol is located:
./lib/x86_64-linux-gnu/libsepol.a
./lib/x86_64-linux-gnu/libsepol.so

Distro:
`$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
`

**Comment by jakev** [comment]
Are you using master? I ran into this issue a couple of weeks ago and submitted a pull request that was merged: https://github.com/TresysTechnology/setools/commit/1655fb7e56929c08deaa85133881b3ee80721ea9

**Comment by williamcroberts** [comment]
No I am checked out on 4.0,

**Comment by eismog** [comment]
I also got the error.

>LOG:
~/tool/setools (master) $ git checkout 4.0
 ~/tool/setools (4.0) $ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    static_sepol = dynamic_sepol.replace(".so", ".a")
AttributeError: 'NoneType' object has no attribute 'replace'
 ~/tool/setools (4.0) $

**Comment by eismog** [comment]
I added the right path to setup.py for fixing(ubuntu 16.04).
-    dynamic_sepol = UnixCCompiler().find_library_file(['/usr/lib64', '/usr/lib'], 'sepol')
+    dynamic_sepol = UnixCCompiler().find_library_file(['.',
+        '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu'], 'sepol')
