### ISSUE TITLE
When I do "semodule -i myapp.pp" on ubuntu 14.04. it returns error.

### ISSUE THREAD

**Issue by zfyseu** [TresysTechnology/setools#149]
When I do "semodule -i myapp.pp" on ubuntu 14.04. it returns error.it returns with the error:
"libsemanage.semanage_link_sandbox: Could not access sandbox base file /etc/selinux/ubuntu/modules/tmp/base.pp. (No such file or directory).
semodule:  Failed!
"

How to solve the problem?
Thank you!

**Comment by pebenito** [comment]
This is not related to SETools.
