### ISSUE TITLE
sedump - [Errno 0] Error: 'sepolicy'

### ISSUE THREAD

**Issue by gxp18** [TresysTechnology/setools#158]
Hello,

I have tried the sedump tool for both aosp android 6.0.1 and samsung s7. 
In both cases:

`$ sedump sepolicy -o policy.conf
`
Returns the following:

`[Errno 0] Error: 'sepolicy'
`

**Comment by pebenito** [comment]
sedump is a downstream project, so there isn't much that I can do. If you can reproduce with setools itself, please provide output with the `--debug`. Also, Android M has an incompatible sepolicy format if you are compiling setools against the standard libsepol. This incompatible format will not be supported by setools.
