### ISSUE TITLE
Build Error related with filename_trans_state

### ISSUE THREAD

**Issue by Qingtao-Cao** [TresysTechnology/setools#160]
I am building setool git repo against the latest master branch of selinux.git (https://github.com/SELinuxProject/selinux.git), the filename_trans_t structure describes an expanded filename transition rule, so it has no "next" field as in filename_trans_rule_t.

However, the ftrule_query.c and a number of others expects filename_trans_t having a "next" pointer to the next structure, e.g., the line 79 is: fts->cur = fts->cur->next; thus result in build failure.

**Comment by pebenito** [comment]
This is known. SETools needs to be updated for libqpol 2.7.

For reference: https://marc.info/?l=selinux&m=148155690632620&w=2

**Comment by Qingtao-Cao** [comment]
Thanks Chris!

No wonders filename_trans_t has no next field anymore, they are in hashtab instead of a list now.

**Comment by pebenito** [comment]
Fixed in e743d2a0eaaae7d99302dd3099549ca7ad868eab
