### ISSUE TITLE
Install setools4.1.0-rc on ubuntu16.04

### ISSUE THREAD

**Issue by xinlong-song** [TresysTechnology/setools#161]
Please tell me  how to install setools4.1.0-rc on ubuntu16.04,someone can write a detailed record?Thanks !
When i install setools4.1.0-rc on ubuntu16.04,some errors always happen.

$python setup.py build
libqpol/policy_scan.c: In function ‘yy_get_next_buffer’:
libqpol/policy_scan.c:2785:44: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_s
                                            ^
cc1: all warnings being treated as errors
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

How to slove this problem?Anyone can tell me please?

**Comment by iamantony** [comment]
- open setup.py
- find variable "extra_compile_args" (it contain list of gcc flags)
- add to these flags new one: '-Wno-sign-compare'
- try to build setools

**Comment by xinlong-song** [comment]
Thank you very much,I hava builld and installed setools successful.

**Comment by xinlong-song** [comment]
Thank you very much,I hava builld and installed setools successfully.
