### ISSUE TITLE
Build and installation on Ubuntu 16.10 x64

### ISSUE THREAD

**Issue by iamantony** [TresysTechnology/setools#162]
Recently I successfully built and installed SETools (4.1, 6fa3f2cd8337198fc9e3db2c8e11b9d21374607a) on Ubuntu 16.10 x64. During this process I encountered with several problems:
- SETools additionally requires *python-dev* (or *python3-dev*) and *libbz2-dev* packages. Without them you will not be able to successfully finish build process
- on Ubuntu 16.10 x64 *libsepol* will be installed into */usr/lib/x86_64-linux-gnu*. I think this folder could be added to the list of folders *base_lib_dirs* in *setup.py*
- during build of libqpol I got error:
  ```shell
  libqpol/policy_scan.c: In function ‘yy_scan_bytes’:
  libqpol/policy_scan.c:3254:17: error: comparison between signed and unsigned integer expressions [-  Werror=sign-compare]
    for ( i = 0; i < _yybytes_len; ++i )
  ```
  
  I was able to suppress it by adding compiler flag *-Wno-sign-compare* to the list of flags *extra_compile_args* in *setup.py*

I hope this information will be useful.

**Comment by xinlong-song** [comment]
Thank you for your sharing very much! I got same error with you ,your information is very usseful.
