### ISSUE TITLE
"Apol Help" does not find a needed file

### ISSUE THREAD

**Issue by fishilico** [TresysTechnology/setools#165]
When installing apol on a clean system, the menu "Help -> Apol Help" does not open any window. As this commands only spawns an instance of "assistant", I tried to run in it directly:

    $ assistant -collectionFile /usr/lib/python3.6/site-packages/setoolsgui/apol/apol.qhc \
    -showUrl qthelp://com.github.tresystechnology.setools/doc/index.html \
    -show contents -enableRemoteControl

    Error registering documentation file
    '/usr/lib/python3.6/site-packages/setoolsgui/apol/apol.qch':
    Cannot open documentation file /usr/lib/python3.6/site-packages/setoolsgui/apol/apol.qch.

It seems ``apol.qhc`` needs ``apol.qch`` to be installed as well. By inspected these SQLite databases (using ``sqlite3 < /dev/null -bail -batch -cmd .dump apol.qhc`` for example), it appears that the installed ``.qhc`` file only contains some metadata and a reference to the ``.qch`` file, which contains the real (compressed) help files. Also Qt assistant copies every file it uses to ``$HOME/.local/share/QtProject/Assistant/``, so you may need to remove this directory in order to reproduce this bug.

Moreover since commit 42c2bbd60669421e46713b5c277c472719d0b2e5, the help files are packaged with:

    qcollectiongenerator apol.qhcp -o ../setoolsgui/apol/apol.qhc

By doing so, ``apol.qhc`` contains an ugly reference to the qhc directory, as shown in its dump:

    $ sqlite3 < /dev/null -bail -batch -cmd .dump setoolsgui/apol/apol.qhc
    PRAGMA foreign_keys=OFF;
    BEGIN TRANSACTION;
    CREATE TABLE NamespaceTable (Id INTEGER PRIMARY KEY, Name TEXT, FilePath TEXT );
    INSERT INTO "NamespaceTable" VALUES(1,'com.github.tresystechnology.setools','../../qhc/apol.qch');
    [...]

Would it be possible to change the way ``python setup.py build_qhc`` builds ``apol.qhc`` to create it in ``qhc/`` and then copy it (with ``apol.qch``) to ``setoolsgui/apol/``?

System information: Arch Linux x86-64, setools 4.1.0, qt5-tools 5.7.1, python 3.6.0

**Comment by bigon** [comment]
Isn't there a typo between .qch and .qhc? Or is that two different file format?

**Comment by fishilico** [comment]
From grepping qttools source (https://code.qt.io/cgit/qt/qttools.git/), ``.qhc`` seems to mean "Qt Help Collection file" and ``.qch`` "Qt Compressed Help file". Both are SQLite databases but their content differ (only the ``.qch`` file contains help files).

In assistant command line usage message, there are both ``-collectionFile`` for the ``.qhc`` file and ``-register`` for the ``.qch`` file (https://code.qt.io/cgit/qt/qttools.git/tree/src/assistant/assistant/cmdlineparser.cpp?h=5.9#n38).

**Comment by fishilico** [comment]
For information, in Arch Linux package (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=setools&id=66feb63d87b4bd3dc9270b612d30746c60c5cede#n60) I have added:
```
  # Rebuild apol help files
  qcollectiongenerator qhc/apol.qhcp
  cp -f qhc/apol.qhc setoolsgui/apol/apol.qhc
  cp -f qhc/apol.qch setoolsgui/apol/apol.qch
```
These commands make Apol Help work normally.

**Comment by bigon** [comment]
With the default setup.py file, only apol.qhc is copied in /usr/share/apol.

In debian build logs I see no sign of the .qch file being generated or the .qhc. It only takes the one already in the tarball

**Comment by fishilico** [comment]
Yes, you need to run ``python setup.py build_qhc`` to rebuild apol.qhc.

The README documents this (https://github.com/TresysTechnology/setools/blob/master/README.md#rebuilding-the-apol-help-file):
> For convenience, a prebuilt copy of the apol help data file is included. To rebuild this file, the Qt5 development tools are required (particularly, the qcollectiongenerator tool). At the root of the SETools soures, perform the following:
>
>     $ python setup.py build_qhc

**Comment by bigon** [comment]
Bah, I cannot read apparently...

**Comment by pebenito** [comment]
I'm fine with that change (patches welcome)
