### ISSUE TITLE
sesearch --role_trans -b ... returns unexpected results

### ISSUE THREAD

**Issue by doverride** [TresysTechnology/setools#178]
```
# sesearch --role_trans -b cockpit.priv_login
role_transition wheel.role polkit.pkexec.cmd_file:process sysadm.role;
```
Above the query is for conditional rules associated with the cockpit.priv_login boolean but the result returns role transition rules that arent applicable to the query

**Comment by doverride** [comment]
the above may also apply to --range_trans (untested)
the above does not apply to -T (tested)

**Comment by pebenito** [comment]
This is not a bug. Role transitions and range transitions cannot be conditional. The kernel does not support that. SETools only works on the final kernel policy, not CIL.

**Comment by doverride** [comment]
Interesting, I wonder what the technical limitation is for this. What makes range and role transitions any different than type transitions in that respect .. anyhow thanks for clarifying
