### ISSUE TITLE
[Question] Queries to file_contexts

### ISSUE THREAD

**Issue by kamino** [TresysTechnology/setools#49]
Hi @pebenito,

I would like to add parsing and queries for entries in file_contexts. Is this feature interesting for setools or should I start a separate project ? Also, would you recommend me to try to port libsefs from setools3 to setools or it would be easier to start from scracth.

Thanks,

**Comment by pebenito** [comment]
What specific features did you have in mind?

I think it would be simpler implementing from scratch, as Python is so much better for handling the text. Libselinux's matchpathcon() should be considered too. The long term goal is to have no C code in this project.

**Comment by kamino** [comment]
I would like to parse some SEAndroid specific files (`/file_contexts`, `/property_contexts`, etc.), link entries from these files to `sepolicy` entries and have a complete overview of the system. The format of the files are more or less the same.

**Comment by pebenito** [comment]
Sure, I'd definitely welcome features for handling Android-specific policy files.

**Comment by pebenito** [comment]
You can also ask questions in the #selinux IRC channel on irc.freenode.net.
