### ISSUE TITLE
Implement v30 extended permissions support

### ISSUE THREAD

**Issue by pebenito** [TresysTechnology/setools#73]
Implement support for allowxperms, dontauditxperms, etc. rules in v30 policy.

- [X] low-level support (qpol)
- [X] policyrep.terule support
- [X] SELinuxPolicy support
- [x] SELinuxPolicy rule count unit tests
- [X] seinfo support
- [X] TERuleQuery support
- [X] TERuleQuery unit tests
- [X] TERulesDifference support
- [X] TERulesDifference unit tests
- [X] sediff support
- [x] TERuleQueryTab support

**Comment by pebenito** [comment]
This was almost completely implemented by Richard Haines in pebenito/rhaines-xen-xperms@9c63c458bf47ecb47ee067293bddcd949025e314 and pebenito/rhaines-xen-xperms@932b79a4dced6d7bfe3686e1c434fbe96b8d5d58.

It is being completed/revised and may make 4.0.0.

**Comment by jeffvanderstoep** [comment]
Looks like I'm still missing one:

In file included from libqpol/include/qpol/avrule_query.h:34:0,
                 from setools/policyrep/qpol_wrap.c:3006:
libqpol/include/qpol/policy.h:67:30: fatal error: qpol/xperm_query.h: No such file or directory
 #include <qpol/xperm_query.h>
                              ^
compilation terminated.

**Comment by pebenito** [comment]
sediff and apol updates are not yet done, but sesearch should be ready for testing.
