### ISSUE TITLE
man page is installed to /usr even when --prefix is specified in install

### ISSUE THREAD

**Issue by bachradsusi** [TresysTechnology/setools#99]
I wanted to install setools to my home dir for some debugging. So  I run:

    $ export PYTHONPATH=/home/plautrba/bin/setools4/lib64/python3.4/site-packages/
    $ python3 setup.py install --prefix /home/plautrba/bin/setools4
    ...
    copying man/apol.1 -> /usr/share/man/man1
    error: could not create '/usr/share/man/man1/apol.1': Permission denied

**Comment by pebenito** [comment]
Looks like we're being bit by a setuptools bug: https://bitbucket.org/pypa/setuptools/issues/130/install_data-doesnt-respect-prefix

**Comment by pebenito** [comment]
Actually I think what you might want to use is the --root option instead:
```
python setup.py install --root /tmp/foo
[...]
running install_data
creating /tmp/foo/usr/share
creating /tmp/foo/usr/share/man
creating /tmp/foo/usr/share/man/man1
copying man/sesearch.1 -> /tmp/foo/usr/share/man/man1
```

**Comment by bachradsusi** [comment]
That works. Thank!
